# SPDX-License-Identifier: GPL-2.0-only
# Deliberately omit DNS, dynamic module management and optional modules.
set_target_properties(inspircd PROPERTIES SUFFIX ".wasm")
set(WASI_CORE_MODULES channel clients info list lusers message mode oper serialize_rfc stats stub user wallops who whois whowas xline)
set(REGISTRY "#include \"inspircd.h\"\n#include \"wasi/static.h\"\n")
foreach(NAME IN LISTS WASI_CORE_MODULES)
  set(BASE "${PROJECT_SOURCE_DIR}/modules/core/${NAME}")
  if(IS_DIRECTORY "${BASE}")
    file(GLOB SOURCES CONFIGURE_DEPENDS "${BASE}/*.cpp")
  else()
    set(SOURCES "${BASE}.cpp")
  endif()
  add_library(wasi_core_${NAME} OBJECT ${SOURCES})
  target_compile_definitions(wasi_core_${NAME} PRIVATE
    "MODNAME=\"core_${NAME}\"" "INSPIRCD_STATIC_INIT=wasi_init_${NAME}")
  target_sources(inspircd PRIVATE $<TARGET_OBJECTS:wasi_core_${NAME}>)
  string(APPEND REGISTRY "extern \"C\" Module* wasi_init_${NAME}();\n")
endforeach()
string(APPEND REGISTRY "const std::map<std::string, Module* (*)()>& WasiStaticModules() {\nstatic const std::map<std::string, Module* (*)()> modules = {\n")
foreach(NAME IN LISTS WASI_CORE_MODULES)
  string(APPEND REGISTRY "{\"core_${NAME}.so\", wasi_init_${NAME}},\n")
endforeach()
string(APPEND REGISTRY "};\nreturn modules;\n}\n")
file(WRITE "${PROJECT_BINARY_DIR}/wasi-registry.cpp" "${REGISTRY}")
target_sources(inspircd PRIVATE "${PROJECT_BINARY_DIR}/wasi-registry.cpp" wasi/socket.cpp)
